language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
install:
  - "pip install -r requirements_dev.txt"
  - "python setup.py install"
script: py.test -x tests/
branches:
  only:
    - master
